### ISSUE TITLE
.org cors domain needs to be added for fcc and beta

### ISSUE THREAD

**Issue by clandau** [freeCodeCamp/boilerplate-bcrypt#1]
Similar issue as addressed here:
https://github.com/freeCodeCamp/boilerplate-advancednode/pull/1
freeCodeCamp/freeCodeCamp#16915

The problem occurs when attempting to do the BCrypt challenges on beta, all tests fail.
https://beta.freecodecamp.org/en/challenges/information-security-with-helmetjs/understand-bcrypt-hashes
Adding https://www.freecodecamp.org and https://beta.freecodecamp.org to the allowedOrigins array at line 44 of freeCodeCamp/fcctesting.js solves the problem. 

I would be happy to submit a pull request correcting this code if that is ok.

**Comment by Greenheart** [comment]
@clandau Thanks for reporting, and finding a fix!

I'm not up to speed with the current state of these projects, but I do know that a PR is more than welcome. Worst case scenario, we still have a good starting point to discuss and solve these issues ☺️
